name: Test Python App

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - develop
        tags:
           - 'v[0-9]+.[0-9]+.[0-9]+'
    pull_request:
        branches:
            - main
            - develop

jobs:
    test:
        name: Test Django App
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Python Dependencies
              run: cd pokemonapi && pip install -r requirements.txt

            - name: Check Syntax
              run: python manage.py check
            
            - name: Run Tests
              run: python manage.py test

    create-release:
        name: Create App Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs: [test]
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                generateReleaseNotes: true